"""Pydantic request/response models for API endpoints."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel


class ChatMessage(BaseModel):
    """One chat turn in the client-provided conversation history."""

    role: str
    content: str


class DocumentOut(BaseModel):
    """Document metadata returned to the frontend."""

    id: str
    filename: str
    status: str
    created_at: datetime
    size: int
    pages: int
    chunks: int

    @classmethod
    def from_doc(cls, d: Any) -> "DocumentOut":
        """Convert ORM Document row to API-safe shape."""

        return cls(
            id=d.id,
            filename=d.filename,
            status=d.status,
            created_at=d.created_at,
            size=d.size_bytes,
            pages=d.page_count,
            chunks=d.chunk_count,
        )


class DocumentListResponse(BaseModel):
    """Container response for document listing endpoint."""

    documents: list[DocumentOut]


class UploadResponse(BaseModel):
    """Upload response containing generated document id."""

    doc_id: str


class ChatRequest(BaseModel):
    """Payload for single-document chat requests."""

    doc_id: str
    query: str
    history: list[ChatMessage] = []
    api_key: str = ""


class CitationOut(BaseModel):
    """Source snippet metadata attached to assistant answers."""

    source_num: int
    page: int
    score: float
    text: str


class ChatResponse(BaseModel):
    """Assistant answer plus retrieval citations."""

    answer: str
    citations: list[CitationOut]
    chunks_used: int


class CompareAnalyzeRequest(BaseModel):
    """Payload to request structured comparison for two docs."""

    doc_id_a: str
    doc_id_b: str
    api_key: str = ""


class CompareDocLabel(BaseModel):
    """Small descriptor block used in compare responses."""

    filename: str


class KeyDiffItem(BaseModel):
    """One side-by-side difference/contradiction entry."""

    topic: str
    doc_a: str
    doc_b: str


class AnalysisBlock(BaseModel):
    """Structured analysis generated by the LLM."""

    summary: str
    common_themes: list[str] = []
    key_differences: list[KeyDiffItem] = []
    contradictions: list[KeyDiffItem] = []
    recommendation: str = ""


class CompareAnalyzeResponse(BaseModel):
    """Full response for /compare/analyze."""

    doc_a: CompareDocLabel
    doc_b: CompareDocLabel
    analysis: AnalysisBlock


class CompareQueryRequest(BaseModel):
    """Payload for follow-up Q&A across two docs."""

    doc_id_a: str
    doc_id_b: str
    query: str
    api_key: str = ""


class CompareQueryResponse(BaseModel):
    """Answer text for /compare/query."""

    answer: str
